#!/bin/sh
#Script for displaying stuff into dwm
#Oscar Moreno Garza

BATTERY=`acpi | awk -n '{print $4}' | sed -e 's/,//'`
DATE=`date '+%a %d %b %Y %H:%M'`
MPC_SONG=`mpc | head -1`
MPC_STATE=`mpc | sed -n '/^\[/p' | awk -e '{print $1}'`
VOLUME=`amixer get Master | tail -1  | awk -e '{ if ( $6 ~ /^\[on\]$/ ) { print $4 } }' | sed -e 's/\[//' | sed -e 's/\]//'`


if [ "$MPC_STATE" == "[playing]" ]; then
  MPC="$MPC_SONG |"
fi

if [ -z "$VOLUME" ] || [ "$VOLUME" == "0%" ];then
  VOL='Muted |';
else
  VOL="Vol: $VOLUME |"
fi



if [ "$BATTERY" != "100%" ];then
  BAT="Bat: $BATTERY |"
  echo -n "${MPC} ${VOL} ${BAT} ${DATE}"
else
  echo -n "${MPC} ${VOL} ${DATE}"
fi
